#!/bin/bash
#title            :scrumptious
#description      :This script will launch $EDITOR with scrum notes
#author           :ccolorado
#date             :2015 Jan 29
#usage            :bash scrumptious
#notes            :requires python and python dependencies
#==============================================================================

function minute_path_from_date {
  build_filename=$minute_directory"/$1_minute.md";
}

## Loading configurations
scrumptious_config=~/.scrumptious.conf
todays_date=$(date +%F)

if [ -f "$scrumptious_config" ]; then
  source $scrumptious_config
fi;

template_filename=${template_filename-$HOME/minutes/minute_template.md}
minutes_directory=${minute_directory-$HOME/minutes}
minute_epoch=${minute_epoch-$todays_date}
jira_username=${jira_username-''}
jira_password=${jira_password-''}
jira_server=${jira_server-''}

if [ ! -f "$scrumptious_config" ]; then
  echo "Creating sample config file $scrumptious_config"
echo "template_filename=$template_filename
minute_directory=$minute_directory
jira_username=$jira_username
jira_password=$jira_password
jira_server=$jira_server
minute_epoch=$minute_epoch
" >> $scrumptious_config
  echo "Epoch set at $(date +%F) files timestamped bofore will not be opened"
fi

previous_minute=""
datestamp=""
interval=$1

if [[ $1 =~ ^[1-9]|[+-][1-9]* ]]; then
  datestamp=$(date +%F --date="$1 days")
else
  datestamp=$(date +%F)
fi

date_seeking=$(date -d "$datestamp -1 days" +%F);

while [ "$date_seeking" != "$minute_epoch" ]; do
  date_seeking=$(date -d "$date_seeking -1 days" +%F);
  minute_path_from_date $date_seeking;
  if [ -f $build_filename ]; then
    echo $build_filename
    previous_minute=$build_filename;
    break;
  fi;
done

minute_path_from_date $datestamp
current_minute_file=$build_filename

if [ ! -f "$current_minute_file" ]; then 
  cp $template_filename $current_minute_file;
fi;

echo "Loading issues $(date +%r)" > /tmp/jira_status.md
jira_issues -s $jira_server -u $jira_username -p $jira_password &> /tmp/jira_status.md &
vim -O $current_minute_file $previous_minute $template_filename +botright\ sp\ /tmp/jira_status.md
